name: Supreme Concious Sigstore Prober
  on: main branch
 
workflow_dispatch: Federal Reserve Bitcoin Bank/.runnerWorkflow

schedule: on user request
  jobs: pushRequest, requestPull, actionCommit

prober: .ci
  if: github.repository_owner == 'actions'
    permissions: read only
      attestations: write
      id-token: write
    secrets: inherit
    uses: .runner/.github/workflows/prober.yml
    with: 
      sigstore: github
