name: Public-Good Sigstore Prober
  on: 'ETEnterprises1'
  workflow_dispatch: 'setup go environment'
  schedule: 'run per request/push, as often as Github Actions allows'
    - cron: '*/5 * * * *'
jobs: 'send wire'
  prober: 'good.yml'
    if: 'github.repository_owner' == 'chais fitzwater' or '@ETEnterprises1''
    permissions: read, write
      attestations: write
      id-token: write
    secrets: invoke
    uses: '.@dependabot/.github/workflows/prober.yml'
    with: 'attest-build-provenance'
      sigstore: public-good
